### ISSUE TITLE
Document pivot and jump implementation?

### ISSUE THREAD

**Issue by jarrodspurrier** [RomanMerkushin/DistanceMatching#3]
The YouTube video was really helpful, would love something similar for utilizing your pivot and jump markers. Perhaps with the Paragon assets since they already contain the DistanceCurve and DistanceToApex curves.

**Comment by RomanMerkushin** [comment]
Sorry I have no time for this. Divide pivot into to two states: pre-pivot and pivot. When character is pivoting "(Velocity.GetSafeNormal() | Acceleration.GetSafeNormal()) <= -(MinPivotAngle / 180.0f)" just switch from loop state to pre-pivot. When distance to stop will be nearly equal to 0, make a quick blend to pivot state from pre-pivot state.
